import {
  INVARIANT_COUNT,
  SUITE_FILE_COUNT,
  SUITE_FILES,
} from "./invariant-count.generated";

/**
 * The test suite, counted from the test suite.
 *
 * A page that names a number of invariants and gets it from a hand-typed
 * constant is making exactly the unverifiable claim the rest of this site
 * argues against, and it had already gone stale: a footer read 137 while the
 * suite held 208.
 *
 * The count is generated by scripts/count-invariants.mjs and refreshed on
 * every build, rather than read at request time, because the engine page is
 * a client component and node:fs cannot cross that boundary. A test compares
 * the generated figure against a live count, so a stale file fails the suite
 * instead of quietly misreporting on a page.
 */

export interface SuiteGroup {
  /** Path relative to the repository root. */
  file: string;
  /** What this file holds the engine to. */
  subject: string;
  count: number;
}

const SUBJECTS: Record<string, string> = {
  "engine.test.ts": "The causal core: revenue, cost, review load, apprenticeship, liability",
  "demand.test.ts": "Market absorption held apart from the levers a firm controls",
  "configurations.test.ts": "That optimising the headline number walks into a refusal",
  "triage-engine.test.ts": "Workflow selection, and the refusal to rank unmeasured work",
  "sourcing-engine.test.ts": "Build or buy decided on market size, not price",
  "progress-engine.test.ts": "The evidence chain: an unknown link blocks rather than passes",
  "proof-engine.test.ts": "Whether an authorisation still holds",
  "record-engine.test.ts": "Decision records and what voids them",
  "agent-engine.test.ts": "The working agent's own boundaries",
  "prep-engine.test.ts": "Engagement preparation",
  "patterns.test.ts": "Recurring failure shapes",
  "index-lens.test.ts": "The maturity-index reading",
  "model-boundary.test.ts": "That no language model touches any number",
  "act-data.test.ts": "One lever change per act, and no act repeating a lever state",
  "act-count.test.ts": "That copy naming a count agrees with the data",
  "screen-data.test.ts": "That the return threshold and the outcome differ in sign",
  "sourcing-data.test.ts": "That sourcing moves the cost line and nothing else",
  "nav-data.test.ts": "The route list, and that a first visit is offered three doors and no more",
  "invariants.test.ts": "That this count agrees with the suite it counts",
};

export const SUITE: SuiteGroup[] = SUITE_FILES.map(({ file, count }) => ({
  file,
  count,
  subject: SUBJECTS[file.split("/").pop() ?? file] ?? "Behaviour of this module",
}));

export { INVARIANT_COUNT, SUITE_FILE_COUNT };
