/**
 * GENERATED by scripts/count-invariants.mjs. Do not edit by hand.
 *
 * Regenerated on every build. If this file disagrees with `npm test`, the
 * build that produced it is stale, not the suite.
 */

export interface SuiteFile {
  file: string;
  count: number;
}

export const SUITE_FILES: SuiteFile[] = [
  {
    "file": "lib/engines/progress-engine.test.ts",
    "count": 22
  },
  {
    "file": "lib/engines/proof-engine.test.ts",
    "count": 22
  },
  {
    "file": "lib/engines/agent-engine.test.ts",
    "count": 18
  },
  {
    "file": "lib/engines/engine.test.ts",
    "count": 17
  },
  {
    "file": "lib/engines/record-engine.test.ts",
    "count": 16
  },
  {
    "file": "lib/engines/continuum-engine.test.ts",
    "count": 15
  },
  {
    "file": "lib/engines/prep-engine.test.ts",
    "count": 13
  },
  {
    "file": "lib/engines/triage-engine.test.ts",
    "count": 13
  },
  {
    "file": "lib/nav-data.test.ts",
    "count": 13
  },
  {
    "file": "lib/engines/model-boundary.test.ts",
    "count": 12
  },
  {
    "file": "lib/engines/demand.test.ts",
    "count": 10
  },
  {
    "file": "lib/engines/sourcing-engine.test.ts",
    "count": 10
  },
  {
    "file": "components/run/act-data.test.ts",
    "count": 8
  },
  {
    "file": "lib/engines/configurations.test.ts",
    "count": 8
  },
  {
    "file": "lib/engines/patterns.test.ts",
    "count": 7
  },
  {
    "file": "components/sourcing/sourcing-data.test.ts",
    "count": 6
  },
  {
    "file": "lib/engines/index-lens.test.ts",
    "count": 6
  },
  {
    "file": "components/room/charter.test.ts",
    "count": 5
  },
  {
    "file": "components/triage/screen-data.test.ts",
    "count": 5
  },
  {
    "file": "lib/engines/invariants.test.ts",
    "count": 3
  },
  {
    "file": "components/run/act-count.test.ts",
    "count": 2
  }
];

export const INVARIANT_COUNT = 231;

export const SUITE_FILE_COUNT = 21;
